apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-managing
  namespace: nepremicnine
spec:
  selector:
    matchLabels:
      app: user-managing
  template:
    metadata:
      labels:
        app: user-managing
    spec:
      containers:
        - name: user-managing
          image: potocnikvid/nepremicnine-user-managing
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUPABASE_SERVICE_ROLE_KEY
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUPABASE_KEY
            - name: SUPABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUPABASE_JWT_SECRET
            - name: USER_MANAGING_SERVER_PORT
              value: "8080"
            - name: USER_MANAGING_SERVER_MODE
              value: "release"
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: FRONTEND_URL
          resources:
            limits:
              cpu: "0.1"
              memory: "256Mi"
            requests:
              cpu: "0.01"
              memory: "32Mi"
          readinessProbe:
            httpGet:
              path: /user-managing/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /user-managing/health/general
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10