apiVersion: v1
kind: Service
metadata:
  name: property-managing
  namespace: nepremicnine
  labels:
    app: property-managing
spec:
  type: ClusterIP
  selector:
    app: property-managing
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080